NUM_CLASSES = 5
UNIFORM_PROBABILITY = [1.0 / NUM_CLASSES] * NUM_CLASSES
IMAGE_HEIGHT = 250
IMAGE_WIDTH = 250
IMAGE_CHANNELS = 3
IMAGE_SHAPE = (IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS)
PROCESSED_IMAGE_SHAPE = (IMAGE_CHANNELS, IMAGE_HEIGHT, IMAGE_WIDTH)
IMAGE_SIZE = (IMAGE_HEIGHT, IMAGE_WIDTH)

BRIGHTNESS_MIN = 0
BRIGHTNESS_MAX = 255
RICE_RECT_TOP_LEFT = (50, 50)
RICE_RECT_BOTTOM_RIGHT = (200, 200)
ROTATION_ANGLE = 45
MID_BRIGHTNESS = 128
RICE_BRIGHTNESS = 200
EXPECTED_BRIGHTNESS_APPROX = 137.0

PIXEL_MIN_VALUE = 0
PIXEL_MAX_VALUE = 255
NORMALIZED_MIN = 0.0
NORMALIZED_MAX = 1.0
INVALID_IMAGE_HEIGHT = 300
INVALID_IMAGE_WIDTH = 300
INVALID_IMAGE_SHAPE = (INVALID_IMAGE_HEIGHT, INVALID_IMAGE_WIDTH, IMAGE_CHANNELS)

DUMMY_IMAGE_PATH = "dummy/image/path.jpg"
TEST_IMAGE_NAME = "test_image.jpg"
NONEXISTENT_PATH = "nonexistent_file.jpg"
